name: RSync Code Git

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your workflow can access it
      - uses: actions/checkout@v2
            
      #Rsync Deployment section 
      - name: rsync deployments
        uses: midhlajvs/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: src/
          remote_path: /var/www/html/test/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
